

name: Trigger common workflow

on:
  push:
    branches:
      - main
  

jobs:
  trigger_common_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger common workflow
        uses: actions/checkout@v2
      - name: Dispact workflow in the common repository
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: aditi7gupta7/github-action-common-repo-final
