name: Trigger common workflow

on:
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: use common workflow
        uses: actions/checkout@v2
        with: 
          repository: aditi7gupta7/github-action-common-repo-final
          ref: main
          path: .github/workflows
          token: ${{ secrets.COMMON_REPO_PAT }}

