name: MY java workflow

on:
  push:
    branches: [ "main" ]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Run Shared Action
      uses: com-repo-3-35/.github/workflows/main
