name: Trigger common workflow

on:
  push:
    branches:
      - main
  

jobs:
  trigger_common_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger common workflow
	    run: |
        curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token $COMMON_REPO_PAT \
          https://api.github.com/repos/aditi7gupta7/github-action-common-repo-final/dispatches
